[main]
font=RobotoMono Nerd Font:size=14
#font=SFMono Nerd Font:size=14
#font=JetBrainsMono Nerd Font:size=14
#font=Fixed:size=12
#font=lemon:size=8
#font=scientifica:size=8
#font=Cozette:size=8
#font=Lavender Nerd:size=12
#font=creep:size=12
#font=Gallant12:size=15
pad=33x33
